# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Stage-1
    displayName: Stage-1
    jobs:  
    - job: Build-1
      displayName: Build-1
      steps:
        - task: AzureCLI@2
          displayName: Azure CLI
          inputs:
            azureSubscription: djr-msft-dev
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az --version
              az account show
